#!/usr/bin/python

import sys
from os import listdir
from os.path import isfile, join

if(len(sys.argv) < 2):
	print "tpz_overhead path"
	exit(1);
 
path = sys.argv[1];
print path

# From pin_util.h
tmap = {
	0: "topaz",
	1: "main",
	2: "comm",
	3: "send",
	4: "task",
	5: "serialize",
	6: "topaz-transform",
	7: "topaz-detect"
}

def read_time_profile(path):
	h = open(path,'r')
	
	timers={};
	cnts={};
	for k in tmap.keys():
		timers[tmap[k]] = 0;
		cnts[tmap[k]] = 0;
		
	for line in h:
		try:
			entries = line.split('\t')
			iid = int(entries[0]);
			cnt = float(entries[1]);
			id = tmap[iid];
			if id not in timers:
				timers[id] = 0;
				cnts[id] = 0;
				
			timers[id]+=cnt;
			cnts[id]+=1;
		except ValueError:
			print "TIME: skipping line."
	result = {};
	result["timers"] = timers;
	result["cnts"] = cnts;
	return result;

def read_comm_profile(path):
	h = open(path,'r');
	sent_val = 0;
	recv_val = 0;
	n = 0;
	for line in h:
		try:
			entries = line.split('\t');
			taskset = int(entries[0]);
			task = int(entries[1]);
			sdat = int(entries[2]);
			rdat = int(entries[3]);

			sent_val += sdat;
			recv_val += rdat;
			n+=1;
			
		except ValueError:
			print "COMM: skipping line"
	
	
			
	result = {};
	# average per/task communication overhead
	result["sent"] = float(sent_val)/n;
	result["recvd"] = float(recv_val)/n;
	return result;

def analyze_overhead(m,mc,w,wc):
	#print "	#Main"
	print wc
	print mc
	print "" 
	ser_overhead = (1.0*wc['comm'])/(mc['task']+ wc['task']);
	print "Serialization Overhead (Ser:Task)",ser_overhead 
		
def avg(key,m,w,mc,wc):
	n = (mc['task'] + wc['task']);
	if n == 0:
		return 0;
	return (w[key])/n;

def cum(key,m,w,mc,wc):
	return m[key] + w[key];


def ratio(v,base):
	return str(float(v)/base) + ":" + str(1) + "    ("+str(v)+","+str(base)+")";
	
def analyze(d, c):
	#topaz timer: includes comm
	#comm timer: includes send
	#main timer: includes topaz,comm,send
	t_m = d[0]['data']['timers']; t_w = d[1]['data']['timers']
	t_mc = d[0]['data']['cnts']; t_wc = d[1]['data']['cnts']
	c_m = c[0]['data']; c_w = c[1]['data'];
	cum_task = cum('task',t_m,t_w,t_mc,t_wc);
	cum_reexec = cum('task',t_m,{'task':0},t_mc,{'task':0})
	cum_detect = cum('topaz-detect',t_m,t_w,t_mc,t_wc);
	cum_transform = cum('topaz-transform',t_m,t_w,t_mc,t_wc);
	cum_topaz = cum('topaz',t_m,t_w,t_mc,t_wc);
	cum_main = cum('main',t_m,t_w,t_mc,t_wc);
	cum_sent = c_m['sent']
	cum_recv = c_w['sent']
	print "### Totals"
	print "Task: "+str(cum_task)
	print "Reexec: "+str(cum_reexec)
	print "Detect: "+str(cum_detect)
	print "Transform: "+str(cum_transform)
	print "Topaz: "+str(cum_topaz)
	print "Main: "+str(cum_main)
	print "cum Input Data (bytes): "+str(cum_sent)
	print "cum Output Data (bytes): "+str(cum_recv)
	print ""
	print ""
	avg_task = avg('task',t_m,t_w,t_mc,t_wc);
	avg_reexec = avg('task',t_m,{'task':0},t_mc,{'task':0})
	avg_detect = avg('topaz-detect',t_m,t_w,t_mc,t_wc);
	avg_transform = avg('topaz-transform',t_m,t_w,t_mc,t_wc);
	avg_topaz = avg('topaz',t_m,t_w,t_mc,t_wc);
	avg_main = avg('main',t_m,t_w,t_mc,t_wc);
	avg_sent = c_m['sent']
	avg_recv = c_w['sent']
	print "### Averages"
	print "Task: "+str(avg_task)
	print "Reexec: "+str(avg_reexec)
	print "Detect: "+str(avg_detect)
	print "Transform: "+str(avg_transform)
	print "Topaz: "+str(avg_topaz)
	print "Main: "+str(avg_main)
	print "Avg Input Data (bytes): "+str(avg_sent)
	print "Avg Output Data (bytes): "+str(avg_recv)
	print ""
	print ""
	print "### Average Ratios (:Task Instruction)"
	print "Reexec: "+ratio(avg_reexec, avg_task)
	print "Detect: "+ratio(avg_detect, avg_task)	
	print "Transform: "+ratio(avg_transform, avg_task)
	print "Topaz: "+ratio(avg_topaz, avg_task)
	print "Main: "+ratio(avg_main, avg_task)
	print "Data (bytes/inst): "+ratio(avg_sent + avg_recv, avg_task)
	print ""
	print "###Total Ratios (:Task Instruction)"
	print "Reexec: "+ratio(cum_reexec, cum_task)
	print "Detect: "+ratio(cum_detect, cum_task)	
	print "Transform: "+ratio(cum_transform, cum_task)
	print "Topaz: "+ratio(cum_topaz, cum_task)
	print "Main: "+ratio(cum_main, cum_task)
	print "Data (bytes/inst): "+ratio(cum_sent + cum_recv, cum_task)
	print ""
	print "### OTHER"
	overhead_topaz = cum_topaz / (cum_main+cum_task);
	overhead_det = (cum_detect + cum_transform) / (cum_main+cum_task);
	overhead_reexec = (cum_reexec) / (cum_main+cum_task);
	
	print "Topaz Overhead: "+str(overhead_topaz)
	print "Detect Overhead: "+str(overhead_det)
	print "Reexec Overhead: "+str(overhead_reexec)
	
	sram_savings = 0.8
	dram_savings = 0.33
	frac_dram = 0.4
	frac_energy_consump = 0.7009
	
	
	
def read():
	timers_list = {};
	comm_list = {};
	for f in listdir(path):
		if isfile(join(path,f)):
			profile = {};
			if((f.split('.')[0]) == "timer"):
				profile["path"] = join(path,f)
				profile["id"] = int(f.split('.')[1]);
				profile["data"] = read_time_profile(join(path,f));
				timers_list[profile["id"]] = profile;
			elif(f.split('.')[0] == "comm"):
				profile["path"] = join(path,f)
				profile["id"] = int(f.split('.')[1]);
				profile["data"] = read_comm_profile(join(path,f));
				comm_list[profile["id"]] = profile;
				#print profile_list.keys();
		#print profile_list
	return timers_list,comm_list;

timers,comms = read();
print comms
analyze(timers, comms);
