
all: make-all

make-all:	
	cd common; make
	cd runner; make
	cd log-reader; make
	cd checker; make
	cd scheduler; make
	cd classifier; make

clean:
	cd common; make clean
	cd runner; make clean
	cd log-reader; make clean
	cd checker; make clean
	cd scheduler; make clean
	cd classifier; make clean
